--TASK 3 done by Srinithi R
USE TechShop;

--1 to retrieve a list of all orders along with customer information (e.g., customer name) for each order
SELECT O.OrderID, O.OrderDate, C.FirstName,C.Email, C.Phone
FROM Orders O
FULL JOIN Customers C ON O.CustomerID = C.CustomerID;

--2  to find the total revenue generated by each electronic gadget product.
SELECT p.ProductName, SUM(od.Quantity * p.Price) AS TotalRevenue
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalRevenue DESC;


--3 to list all customers who have made at least one purchase
SELECT DISTINCT C.FirstName, C.Email, C.Phone
FROM Customers C
INNER JOIN Orders O ON C.CustomerID = O.CustomerID;

--4 to find the most popular electronic gadget, which is the one with the highest total quantity ordered
SELECT TOP 1 p.ProductName, SUM(od.Quantity) AS TotalQuantityOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY  p.ProductName
ORDER BY TotalQuantityOrdered DESC;

--5 to retrieve a list of electronic gadgets along with their corresponding categories
ALTER TABLE Products
ADD Category VARCHAR(50);
UPDATE Products
SET Category = 'Electronics'
WHERE ProductName IN ('Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Keyboard', 'Mouse', 'Monitor', 'Printer', 'Router', 'Webcam');
SELECT *FROM Products;

--6 to calculate the average order value for each customer
SELECT C.FirstName, AVG(O.TotalAmount) AS AvgOrderValue
FROM Customers C
JOIN Orders O ON C.CustomerID = O.CustomerID
GROUP BY C.FirstName;

--7 to find the order with the highest total revenue
SELECT TOP 1 O.OrderID, C.FirstName, O.TotalAmount
FROM Orders O
JOIN Customers C ON O.CustomerID = C.CustomerID
ORDER BY O.TotalAmount DESC;

--8 to list electronic gadgets and the number of times each product has been ordered
SELECT P.ProductName, COUNT(OD.OrderID) AS Number_of_times_ordered
FROM Products P
JOIN OrderDetails OD ON P.ProductID = OD.ProductID
GROUP BY P.ProductName;

--9 to find customers who have purchased a specific electronic gadget product
DECLARE @ProductName NVARCHAR(100);  
SET @ProductName = 'Laptop';  

SELECT C.FirstName
FROM Customers C
JOIN Orders O ON C.CustomerID = O.CustomerID
JOIN OrderDetails OD ON O.OrderID = OD.OrderID
JOIN Products P ON OD.ProductID = P.ProductID
WHERE P.ProductName = @ProductName;

--10 to calculate the total revenue generated by all orders placed within a specific time period
DECLARE @StartDate DATE, @EndDate DATE;  
SET @StartDate = '2024-01-01';  
SET @EndDate = '2024-12-31';    

SELECT SUM(O.TotalAmount) AS TotalRevenue
FROM Orders O
WHERE O.OrderDate BETWEEN @StartDate AND @EndDate;









