use TechShop
--1 customers not places orders
select c.FirstName,c.LastName,c.Email,c.Phone from Customers c left join 
Orders o on c.CustomerID = o.CustomerID where o.OrderID is null;


--2 total number of products avalaible for sales
select count(*) as TotalProducts_forSale from Products

--3 Total Revenue generated by techshop
select sum(od.Quantity * p.Price) as TotalRevenue from OrderDetails od  join Products p on od.ProductID = p.ProductID;


--4 average quantity order for product
 select avg(od.Quantity) as AverageQuantity from OrderDetails od 
 join Products p on od.ProductID = p.ProductID where p.Description = 'Electronic Gadgets%';

 --5 total revenue generated by a specific Customer

 select sum(od.Quantity * p.Price) as TotaRevenue from Orders o join 
 OrderDEtails od on o.OrderID = od.OrderID join Products p on od.ProductID = p.ProductID where 
 o.CustomerID = 10;
  
  --6 Customer who have placed the max orders

  select c.firstName,c.LastName ,count(o.OrderId) as NumberOfOrders From Customers c join Orders o  
  on c.CustomerID = o.CustomerID Group by c.CustomerID,c.firstName,c.LastName
  order by NumberOfOrders desc offset 0 rows fetch next 1 rows only;


  --7 mostPopular product category
  select p.Description as Category,sum(od.Quantity)as TotalQuantityOrdered from Products p 
  join  OrderDetails od on p.ProductID = od.ProductID group by p.Description Order by TotalQuantityOrdered desc
  offset 0 rows fetch next 1 rows only;
  

  --8 ustomer who has spent the max money on Electronic Gadgets
select c.FirstName,c.LastName, sum(od.Quantity*p.Price) as TotalSpent from 
Customers c join Orders o on c.CustomerID = o.CustomerID join OrderDEtails od 
on o.OrderID = od.OrderID join Products p on od.ProductID =p.ProductID
where p.Description = 'Electronic Gadgets'group by c.CustomerID,c.FirstName,c.LastName
Order by TotalSpent desc  offset 0 rows fetch next 1 rows only;
select * from Products where Description like'Electronic Gadgets%';

--9 calculate average orderv value

select avg(o.TotalAmount) as AverageOrdeValue from Orders o;

--10 total number of orders by each customer
select c.FirstName,c.LastName, count(o.OrderID) as OrderCount from Customers c join
Orders o on c.CustomerID = o.CustomerID group by c.CustomerID,c.FirstName,c.LastName;